[package]
name = "mdbook-tabs"
description = "mdBook plugin for rendering content in tabs."
homepage = "https://mdbook-plugins.rustforweb.org/tabs.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
mdbook.workspace = true
mdbook-plugin-utils = { path = "../mdbook-plugin-utils", version = "0.2.1" }
pulldown-cmark.workspace = true
semver.workspace = true
serde.workspace = true
serde-keyvalue = "0.1.0"
serde_json.workspace = true
