[book]
authors = ["Daniëlle Huisman"]
language = "en"
multilingual = false
src = "src"
title = "mdBook Plugins"

[preprocessor.trunk]
command = "cargo run -p mdbook-trunk"

[output.trunk]
command = "cargo run -p mdbook-trunk"
