[book]
authors = ["Daniëlle Huisman"]
language = "en"
multilingual = false
src = "src"
title = "mdBook Plugins"

[preprocessor.tabs]
command = "cargo run -p mdbook-tabs"

[preprocessor.trunk]
command = "cargo run -p mdbook-trunk"

[output.html]
additional-css = ["theme/tabs.css", "theme/trunk.css"]
additional-js = ["theme/tabs.js", "theme/trunk.js"]

[output.trunk]
command = "cargo run -p mdbook-trunk"
serve = true

[rust]
edition = "2024"
