name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: RustForWeb/.github/.github/workflows/commits.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1

    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1
        with:
            target: wasm32-unknown-unknown
