name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    commits:
        name: Commits
        uses: RustForWeb/.github/.github/workflows/commits.yml@b12847e2aa8dede8174ffff5f1ecf932699aeac8 # v1.0.0

    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@b12847e2aa8dede8174ffff5f1ecf932699aeac8 # v1.0.0
        with:
            target: wasm32-unknown-unknown
