name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        name: Publish
        uses: RustForWeb/.github/.github/workflows/publish.yml@300f79f742e86d4653d44a17864e89297a7025cf # v1.0.2
        with:
            enable-rust: true
            enable-typescript: false
