name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        name: Publish
        uses: RustForWeb/.github/.github/workflows/publish.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1
        with:
            enable-rust: true
            enable-typescript: false
