name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write
    packages: write

jobs:
    publish:
        name: Publish
        uses: RustForWeb/.github/.github/workflows/publish.yml@8a0ce4333fd134d177f151cba9b768f041f43601 # v1.0.3
        with:
            enable-rust: true
            enable-typescript: false
