name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

permissions:
    contents: read

jobs:
    pull-request:
        name: Pull Request
        uses: RustForWeb/.github/.github/workflows/pull-request.yml@300f79f742e86d4653d44a17864e89297a7025cf # v1.0.2
