name: Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened, edited]

permissions:
    contents: read

jobs:
    pull-request:
        name: Pull Request
        uses: RustForWeb/.github/.github/workflows/pull-request.yml@8a0ce4333fd134d177f151cba9b768f041f43601 # v1.0.3
