name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: RustForWeb/.github/.github/workflows/release.yml@8a0ce4333fd134d177f151cba9b768f041f43601 # v1.0.3
        with:
            bump: ${{ inputs.bump }}
            bump-rust: true
            bump-typescript: false
            extract-version: 'rust'
        secrets:
            app-client-id: ${{ secrets.APP_ID }}
            app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
