name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    book:
        name: Book
        uses: RustForWeb/.github/.github/workflows/book.yml@8a0ce4333fd134d177f151cba9b768f041f43601 # v1.0.3
