name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    book:
        name: Book
        uses: RustForWeb/.github/.github/workflows/book.yml@dc2442c27ef9f920a1a889ec94e615b419b491b2 # v1.0.1
